title: Traffic Crash Prediction
description: Predicting and analyzing severe crashes in Chicago using machine learning
theme: jekyll-theme-leap-day
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
show_downloads: false
